export const Therapeutic_Area_Map = [
"All",
"Endocrinology",
// "Breast Ptosis",
// "Portosystemic Collateral Veins",
// "Cerebral Cavernous Hemangioma",
// "Impacted Stones",
// "Laparoscopic Gastric Banding",
// "Respiratory Infection Other",
// "Prostatectomy",
// "Stable Angina (SA)",
// "Cervical Lymphadenopathy",
// "Neoplasms/Therapy",
// "Obese Patients With Prostate Cancer Disease",
// "Spinal Degenerative Disorder",
// "OVCA",
// "Viral Infections After HSCT",
// "Peripheral Post-surgical Neuropathic Pain",
// "Degenerative; Dementia",
// "Diabetes Mellitus in Pregnancy",
// "Malignant Primary Brain Tumors",
// "Stable (MSS) Colon Cancer",
// "Sentinel Lymph Node Biopsy",
// "Invasive Mycosis",
// "Laryngeal Cancer Stage III",
// "Neuromuscular Blockade Reversal Agent",
// "Cost Per Patient Rate",
// "Determination of Death",
// "Brainstem Glioma, Pediatric",
// "Procedural Skill Competency",
// "Invasive Cancer",
]