export const COUNTRY_MAP = [
  "Hungary",
  "Belize",
  "Honduras",
  "Norway",
  "Botswana",
  "Russian Federation",
  "Pakistan",
  "Romania",
  "Brazil",
  "Austria",
  "Guatemala",
  "Guinea-Bissau",
  "Former Serbia and Montenegro",
  "Bolivia",
  "Ethiopia",
  "Niger",
  "Panama",
  "South Sudan",
  "Yemen",
  "Virgin Islands (U.S.)",
  "Lithuania",
  "Moldova, Republic of",
  "Bulgaria",
  "Croatia",
  "Libyan Arab Jamahiriya",
  "Tunisia",
  "Aruba",
  "Sudan",
  "Mali",
  "North Macedonia",
  "Swaziland",
  "Morocco",
  "Myanmar",
  "Nicaragua",
  "Mexico",
  "Guyana",
  "Nepal",
  "Tanzania",
  "Poland",
  "Saint Martin",
  "Greenland",
  "French Guiana",
  "Lebanon",
  "Costa Rica",
  "Jersey",
  "Gibraltar",
  "Haiti",
  "Samoa",
  "Equatorial Guinea",
  "Antigua and Barbuda",
  "Korea, Democratic People's Republic of",
  "Czechia",
  "Somalia",
  "Andorra",
  "Indonesia",
  "Bangladesh",
  "Mayotte",
  "Venezuela",
  "Brunei Darussalam",
  "Federated States of Micronesia",
  "Kiribati",
  "Cameroon",
  "Luxembourg",
  "Czech Republic",
  "Sweden",
  "Montenegro",
  "Uganda",
  "Jordan",
  "Syrian Arab Republic",
  "Dominican Republic",
  "Cambodia",
  "Ireland",
  "Papua New Guinea",
  "Singapore",
  "San Marino",
  "American Samoa",
  "Sri Lanka",
  "Uzbekistan",
  "Portugal",
  "Finland",
  "Malta",
  "Côte D'Ivoire",
  "Colombia",
  "Albania",
  "Cayman Islands",
  "Grenada",
  "Saudi Arabia",
  "Ukraine",
  "Cuba",
  "Latvia",
  "Holy See (Vatican City State)",
  "Palestinian Territories, Occupied",
  "Kyrgyzstan",
  "Iran, Islamic Republic of",
  "Algeria",
  "France",
  "Cape Verde",
  "Réunion",
  "Maldives",
  "Slovakia",
  "Djibouti",
  "Israel",
  "Senegal",
  "Ghana",
  "Malaysia",
  "Kenya",
  "Iceland",
  "Zambia",
  "Madagascar",
  "Kuwait",
  "Hong Kong",
  "Sierra Leone",
  "Liberia",
  "Bosnia and Herzegovina",
  "Philippines",
  "Benin",
  "United States",
  "Cyprus",
  "Guinea",
  "Turkey",
  "Nigeria",
  "Rwanda",
  "Tajikistan",
  "Zimbabwe",
  "Guam",
  "Comoros",
  "Lao People's Democratic Republic",
  "China",
  "Saint Lucia",
  "Macedonia, The Former Yugoslav Republic of",
  "New Caledonia",
  "Belarus",
  "Armenia",
  "Former Yugoslavia",
  "Qatar",
  "Netherlands",
  "Lesotho",
  "Gabon",
  "Paraguay",
  "Martinique",
  "Australia",
  "Dominica",
  "Mauritius",
  "Serbia",
  "Angola",
  "Vanuatu",
  "Bahrain",
  "Netherlands Antilles",
  "Spain",
  "Congo",
  "United Arab Emirates",
  "Georgia",
  "Malawi",
  "Belgium",
  "Monaco",
  "Burundi",
  "Taiwan",
  "Bhutan",
  "Solomon Islands",
  "Montserrat",
  "Thailand",
  "Palestinian Territory, occupied",
  "Togo",
  "Burkina Faso",
  "Faroe Islands",
  "El Salvador",
  "Antarctica",
  "Italy",
  "Uruguay",
  "Oman",
  "Fiji",
  "Congo, The Democratic Republic of the",
  "United Kingdom",
  "Palau",
  "Germany",
  "Eritrea",
  "Canada",
  "Barbados",
  "Saint Vincent and the Grenadines",
  "Bermuda",
  "Namibia",
  "Argentina",
  "Liechtenstein",
  "Azerbaijan",
  "Slovenia",
  "Greece",
  "Egypt",
  "Afghanistan",
  "Bahamas",
  "Chad",
  "Puerto Rico",
  "India",
  "Saint Kitts and Nevis",
  "French Polynesia",
  "Chile",
  "Gambia",
  "Estonia",
  "Vietnam",
  "Korea, Republic of",
  "Suriname",
  "South Africa",
  "Peru",
  "Kazakhstan",
  "Central African Republic",
  "Guadeloupe",
  "United States Minor Outlying Islands",
  "Kosovo",
  "Japan",
  "Denmark",
  "Jamaica",
  "Trinidad and Tobago",
  "Mongolia",
  "Iraq",
  "Mauritania",
  "Mozambique",
  "Northern Mariana Islands",
  "Seychelles",
  "Switzerland",
  "Ecuador",
  "New Zealand",
];
